name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint checker

    strategy:
      matrix:
        node-version: ['12.*']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn --dev

      - name: Run ESLint
        uses: ninosaurus/eslint-check@v5.3.1
        with:
          eslint-config-path: "./.eslintrc.js"
          custom-directory: "./"
          repo-token: ${{secrets.GITHUB_TOKEN}}
